### ISSUE TITLE
Error with /media path

### ISSUE THREAD

**Issue by astercraker** [MASILab/ComparativeCalibration#1]
When run the command
python train_stage1.py --cfg ./config/cifar10_trvaltt/cifar10_imb001_stage1.yaml
i have an error 
OSError: [Errno 30] Read-only file system: '/media'

this error is for this lines 
log_dir: '/media/gaor2/Elements/saved_file/Calibration/MiSLAS/imb001/stage1_imb001/logs'
model_dir: '/media/gaor2/Elements/saved_file/Calibration/MiSLAS/imb001/stage1_imb001/ckps'
code_dir: '/media/gaor2/Elements/saved_file/Calibration/MiSLAS/imb001/stage1_imb001/code'

why need access to write in /media path

**Comment by BennettLandman** [comment]
I am closing the older bug reports as these were missed. We are now better tracking reports across the organization. Please re-open if this continues to be a blocker.
